//// lib/config/site.ts
//export const siteConfig = {
//  name: 'Clínica Veterinaria Docente Universidad Ricardo Palma',
//  shortName: 'Veterinaria URP',
//  description:
//    'Clínica veterinaria en Surco, Lima. Atención 24 horas, consultas, cirugías, vacunas y emergencias para tu mascota. Veterinarios especializados de la Universidad Ricardo Palma.',
//  url: 'https://veterinaria.urp.edu.pe',
//  ogImage: 'https://veterinaria.urp.edu.pe/images/og/og-default.png',
//  phone: '+51975198723',
//  whatsapp: '51975198723',
//  address: {
//    street: 'Av. Las Nazarenas s/n',
//    district: 'Santiago de Surco',
//    city: 'Lima',
//    country: 'PE',
//    postalCode: '15039',
//    mapsUrl: 'https://maps.app.goo.gl/VfR6caRSDnjN2htU6',
//  },
//  hours: {
//    weekdays: '08:00–17:00',
//    saturday: 'No atiende',
//    sunday: 'No atiende',
//    emergency: '08:00–17:00 de lunes a viernes',
//  },
//  keywords: [
//    'veterinaria surco',
//    'veterinario surco',
//    'clínica veterinaria surco',
//    'veterinaria 24 horas surco',
//    'veterinario 24 horas surco',
//    'veterinaria cerca de mi',
//    'veterinario cerca de mi',
//    'veterinaria lima',
//    'clínica veterinaria lima',
//    'veterinaria universidad ricardo palma',
//    'veterinarias en surco',
//    'veterinaria la molina',
//    'veterinaria san borja',
//    'emergencia veterinaria surco',
//    'cirugía veterinaria lima',
//    'vacunas mascotas surco',
//  ],
//  social: {
//    facebook: 'https://www.facebook.com/profile.php?id=61586474769295',
//    instagram: 'https://www.instagram.com/clinicaveterinariadocenteurp/',
//    tiktok: 'https://www.tiktok.com/@clinicavetdocenteurp',
//  },
//}
// lib/config/site.ts
export const siteConfig = {
  name: 'Clínica Veterinaria Docente Universidad Ricardo Palma',
  shortName: 'Veterinaria URP',
  description:
    'Clínica veterinaria en Surco, Lima. Atención 24 horas, consultas, cirugías, vacunas y emergencias para tu mascota. Veterinarios especializados de la Universidad Ricardo Palma.',
  // TEMPORAL — cambiar a 'https://veterinaria.urp.edu.pe' cuando sea el dominio final
  url: 'https://veterinaria.posicionarlima.pe',
  ogImage: 'https://veterinaria.urp.edu.pe/images/og/og-default.png',
  phone: '+51975198723',
  whatsapp: '51975198723',
  address: {
    street: 'Av. Las Nazarenas s/n',
    district: 'Santiago de Surco',
    city: 'Lima',
    country: 'PE',
    postalCode: '15039',
    mapsUrl: 'https://maps.app.goo.gl/VfR6caRSDnjN2htU6',
  },
  hours: {
    weekdays: '08:00–17:00',
    saturday: 'No atiende',
    sunday: 'No atiende',
    emergency: '08:00–17:00 de lunes a viernes',
  },
  keywords: [
    'veterinaria surco',
    'veterinario surco',
    'clínica veterinaria surco',
    'veterinaria 24 horas surco',
    'veterinario 24 horas surco',
    'veterinaria cerca de mi',
    'veterinario cerca de mi',
    'veterinaria lima',
    'clínica veterinaria lima',
    'veterinaria universidad ricardo palma',
    'veterinarias en surco',
    'veterinaria la molina',
    'veterinaria san borja',
    'emergencia veterinaria surco',
    'cirugía veterinaria lima',
    'vacunas mascotas surco',
  ],
  social: {
    facebook: 'https://www.facebook.com/profile.php?id=61586474769295',
    instagram: 'https://www.instagram.com/clinicaveterinariadocenteurp/',
    tiktok: 'https://www.tiktok.com/@clinicaveterinariadocenteurp',
  },
}